# Generated by Django 4.0.4 on 2022-09-02 09:36

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('author',))),
                ('author', models.CharField(max_length=255, verbose_name='Автор(ы)')),
                ('author_description', models.TextField(verbose_name='Описание автора / издательства')),
                ('photo', models.ImageField(upload_to='books_photos', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.TextField(verbose_name='Вид книги')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house', models.TextField(verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Read_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='Статус')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phil.books')),
                ('booktype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phil.booktype', verbose_name='Вид книги')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phil.books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замеров')),
                ('Shoulders', models.IntegerField(verbose_name='Плечи, см.')),
                ('Chest', models.IntegerField(verbose_name='Грудь, см.')),
                ('Waist', models.IntegerField(verbose_name='Талия, см.')),
                ('Buttocks', models.IntegerField(verbose_name='Ягодицы, см.')),
                ('Hips', models.IntegerField(verbose_name='Бёдра, см.')),
                ('Weight', models.IntegerField(verbose_name='Вес, кг.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='publishing_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phil.publishing_house', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('user',))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='article_photos', verbose_name='Фотография')),
                ('text', models.TextField(blank=True, verbose_name='Статья')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
