# Generated by Django 4.0.4 on 2022-09-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phil', '0003_measurements_delete_measurements1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'ordering': ['Date'], 'verbose_name': 'Замеры тела', 'verbose_name_plural': 'Замеры тела'},
        ),
    ]
