# Generated by Django 3.2.12 on 2022-11-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phil', '0004_alter_measurements_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-id'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
    ]
