# Generated by Django 3.2.7 on 2023-01-16 17:30

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phil', '0006_auto_20221229_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'ordering': ['-Date'], 'verbose_name': 'Body measurements', 'verbose_name_plural': 'Body measurements'},
        ),
        migrations.AddField(
            model_name='measurements',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='Date', unique_with=('user',)),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Buttocks',
            field=models.IntegerField(verbose_name='Buttocks, sm.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Chest',
            field=models.IntegerField(verbose_name='Chest, sm.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Hips',
            field=models.IntegerField(verbose_name='Hips, sm.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Shoulders',
            field=models.IntegerField(verbose_name='Shoulders, sm.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Waist',
            field=models.IntegerField(verbose_name='Waist, sm.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Weight, kg.'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
