# Generated by Django 3.2.7 on 2023-01-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phil', '0007_auto_20230116_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='slug',
        ),
        migrations.AddField(
            model_name='measurements',
            name='Buttocks_en',
            field=models.IntegerField(null=True, verbose_name='Buttocks, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Buttocks_ru',
            field=models.IntegerField(null=True, verbose_name='Buttocks, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Chest_en',
            field=models.IntegerField(null=True, verbose_name='Chest, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Chest_ru',
            field=models.IntegerField(null=True, verbose_name='Chest, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Date_en',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Date_ru',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Hips_en',
            field=models.IntegerField(null=True, verbose_name='Hips, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Hips_ru',
            field=models.IntegerField(null=True, verbose_name='Hips, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Shoulders_en',
            field=models.IntegerField(null=True, verbose_name='Shoulders, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Shoulders_ru',
            field=models.IntegerField(null=True, verbose_name='Shoulders, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Waist_en',
            field=models.IntegerField(null=True, verbose_name='Waist, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Waist_ru',
            field=models.IntegerField(null=True, verbose_name='Waist, sm.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Weight_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Weight, kg.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='Weight_ru',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Weight, kg.'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
