# Generated by Django 4.0.4 on 2022-09-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phil', '0002_rename_measurements_measurements1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Дата замеров')),
                ('Shoulders', models.IntegerField(verbose_name='Плечи, см.')),
                ('Chest', models.IntegerField(verbose_name='Грудь, см.')),
                ('Waist', models.IntegerField(verbose_name='Талия, см.')),
                ('Buttocks', models.IntegerField(verbose_name='Ягодицы, см.')),
                ('Hips', models.IntegerField(verbose_name='Бёдра, см.')),
                ('Weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Вес, кг.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
        ),
        migrations.DeleteModel(
            name='Measurements1',
        ),
    ]
