# Generated by Django 3.2.12 on 2022-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20221209_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
